import colors from '../../color-scheme.json' assert { type: 'json' };

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: colors.colors.primary,
        secondary: colors.colors.secondary,
        neutral: colors.colors.neutral,
        success: colors.colors.semantic.success,
        warning: colors.colors.semantic.warning,
        error: colors.colors.semantic.error,
        info: colors.colors.semantic.info,
        // CSS variables for theme-aware colors
        'bg-primary': 'var(--background-primary)',
        'bg-secondary': 'var(--background-secondary)',
        'bg-tertiary': 'var(--background-tertiary)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'border-default': 'var(--border-default)',
        'border-focus': 'var(--border-focus)',
        'card-bg': 'var(--card-bg)',
        'card-border': 'var(--card-border)',
        'input-bg': 'var(--input-bg)',
        'input-border': 'var(--input-border)',
        'input-text': 'var(--input-text)',
        'input-placeholder': 'var(--input-placeholder)',
        'btn-primary-bg': 'var(--button-primary-bg)',
        'btn-primary-text': 'var(--button-primary-text)',
        'btn-primary-hover': 'var(--button-primary-hover)',
        'btn-primary-active': 'var(--button-primary-active)',
        'btn-secondary-bg': 'var(--button-secondary-bg)',
        'btn-secondary-text': 'var(--button-secondary-text)',
        'btn-secondary-hover': 'var(--button-secondary-hover)',
        'btn-secondary-active': 'var(--button-secondary-active)',
        'btn-ghost-bg': 'var(--button-ghost-bg)',
        'btn-ghost-text': 'var(--button-ghost-text)',
        'btn-ghost-hover': 'var(--button-ghost-hover)',
        'btn-ghost-active': 'var(--button-ghost-active)',
        'btn-outline-bg': 'var(--button-outline-bg)',
        'btn-outline-text': 'var(--button-outline-text)',
        'btn-outline-border': 'var(--button-outline-border)',
        'btn-outline-hover': 'var(--button-outline-hover)',
        // Additional color scheme variables
        'primary-50': 'var(--primary-50)',
        'primary-500': 'var(--primary-500)',
        'primary-600': 'var(--primary-600)',
        'primary-700': 'var(--primary-700)',
        'primary-900': 'var(--primary-900)',
        'secondary-50': 'var(--secondary-50)',
        'secondary-100': 'var(--secondary-100)',
        'secondary-500': 'var(--secondary-500)',
        'secondary-600': 'var(--secondary-600)',
        'secondary-700': 'var(--secondary-700)',
        'accent-500': 'var(--accent-500)',
        'accent-600': 'var(--accent-600)',
        'success-light': 'var(--success-light)',
        'success-default': 'var(--success-default)',
        'success-dark': 'var(--success-dark)',
        'warning-light': 'var(--warning-light)',
        'warning-default': 'var(--warning-default)',
        'warning-dark': 'var(--warning-dark)',
        'error-light': 'var(--error-light)',
        'error-default': 'var(--error-default)',
        'error-dark': 'var(--error-dark)',
        'info-light': 'var(--info-light)',
        'info-default': 'var(--info-default)',
        'info-dark': 'var(--info-dark)',
      },
    },
  },
  plugins: [],
};
